version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    port:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid


# esta é uma versão 'traduzida' do comando usado para criar o banco
# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e POSTGRESQL_DATABASE=apisolid -p 5432:5432  bitnami/postgresql
# podemos subir o banco com 'docker compose up -d'